spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost

redis:
  channels:
    fund-raised: fund_raised_channel
    project-view: project_view_channel

server:
  port: 8082

logging:
  level:
    root: info

calculations_messages_processing:
  enabled: true

services:
  s3:
    endpoint: http://localhost:9000
    accessKey: user
    secretKey: password
    bucketName: corpbucket

  payment-service:
    host: http://localhost
    port: 9080
  user-service:
    host: http://localhost
    port: 8080

cover-image:
  maxWidth: 1080
  maxHeightHorizontal: 566
  maxHeightSquare: 1080
  maxFileSize: 5242880

app:
  name: "werewolf-project-service"
  timezone: "Europe/Moscow"

calendar:
  id: whatever
  type-of-send-updates: "all"
  oauth:
    local:
      server:
        port: 8888