name: Check unit tests

on:
  pull_request:
    branches:
      - feature-BJS2-43455-DD

jobs:
  job_unit_tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      postgres:
        image: postgres:13.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Install required locales
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen ru_RU.UTF-8
          sudo locale-gen en_US.UTF-8
          sudo update-locale

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          sudo update-locale LANG=ru_RU.UTF-8
          export LANG=ru_RU.UTF-8
          ./gradlew build --no-daemon -x test

      - name: Run Tests
        if: always()
        run: |
          sudo update-locale LANG=ru_RU.UTF-8
          export LANG=ru_RU.UTF-8
          ./gradlew test --no-daemon

      - name: Save logs
        if: failure() || success()
        uses: actions/upload-artifact@v4
        with:
          name: User service tests reports
          path: build/reports/tests/test/